AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 3 API - app.goog1e::chyunyea-backend
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  # HTTP API Gateway
  ChyunYeaHttpApi:
    Properties:
      CorsConfiguration:
        #AllowCredentials: true
        AllowHeaders:
          - Authorization
        AllowMethods:
          - GET
          - DELETE
          - POST
        AllowOrigins:
          - "*"
      Name: ChyunYeaHttpApi
      ProtocolType: HTTP
      Target: !GetAtt ChyunYeaFunction.Arn
    Type: AWS::ApiGatewayV2::Api
  ChyunYeaFunction:
    Properties:
      # Architectures:
      # - arm64
      CodeUri: .
      Environment:
        Variables:
          LOG_LEVEL: ${LOG_LEVEL}
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_HOST: ${POSTGRES_HOST}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_USER: ${POSTGRES_USER}
          SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      Events:
        # ProxyResource:
        #   Properties:
        #     Method: any
        #     Path: /{proxy+}
        #   Type: Api
        # RootEndpoint:
        #   Properties:
        #     Method: any
        #     Path: /
        #   Type: Api
        HttpApiEvent:
          Properties:
            ApiId: ChyunYeaHttpApi
          Type: HttpApi
      FunctionName: "PawnshopsBackendFunction"
      Handler: app.goog1e.chyunyea.StreamLambdaHandler::handleRequest
      MemorySize: 1024
      Policies: AWSLambdaBasicExecutionRole
      Runtime: java17
      Timeout: 30
    Type: AWS::Serverless::Function

Outputs:
  ChyunYeaApi:
    Description: URL for application
    Export:
      Name: ChyunYeaApi
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com'
